import type { Incident } from "./schema";

/**
 * Twelve hardcoded seed incidents plus two sustainability incidents (14 total).
 *
 * These are pre-triaged — no AI call needed. They demonstrate the
 * system's capabilities across zones, categories, severities, and languages.
 * Two are pre-resolved to show the "resolved" state in the UI.
 *
 * All seeds have `source: "seed"` and are visually labeled as "demo" in the UI.
 */
export const SEED_INCIDENTS: Incident[] = [
  {
    id: "seed-001",
    createdAt: Date.now() - 3600000, // 1 hour ago
    status: "open",
    priority: 85,
    source: "seed",
    originalText: "Gate B ke paas bahut zyada bheed hai, log dhakka de rahe hain",
    category: "crowding",
    severity: 4,
    zone: "north_gate",
    summary_en: "Severe overcrowding near Gate B, people pushing.",
    detected_language: "Hindi",
    recommended_action: "Send crowd stewards to Gate B and open additional lanes.",
    confidence: 0.9,
  },
  {
    id: "seed-002",
    createdAt: Date.now() - 3200000,
    status: "open",
    priority: 80,
    source: "seed",
    originalText: "La rampa para sillas de ruedas del lado este está bloqueada por cajas",
    category: "accessibility",
    severity: 3,
    zone: "east_stand",
    summary_en: "Wheelchair ramp on the east side blocked by boxes.",
    detected_language: "Spanish",
    recommended_action: "Dispatch staff to clear the east stand ramp immediately.",
    confidence: 0.92,
  },
  {
    id: "seed-003",
    createdAt: Date.now() - 2800000,
    status: "open",
    priority: 90,
    source: "seed",
    originalText: "Someone collapsed near the south gate, they look unconscious",
    category: "medical",
    severity: 5,
    zone: "south_gate",
    summary_en: "Person collapsed and unconscious near the south gate.",
    detected_language: "English",
    recommended_action: "Dispatch medical team to south gate immediately. Call emergency services.",
    confidence: 0.97,
  },
  {
    id: "seed-004",
    createdAt: Date.now() - 2400000,
    status: "open",
    priority: 75,
    source: "seed",
    originalText: "فقدت ابني بالقرب من منطقة المشجعين، يرتدي قميص الأرجنتين الأحمر",
    category: "lost_person",
    severity: 4,
    zone: "fan_zone",
    summary_en: "Child lost near the fan zone, wearing a red Argentina shirt.",
    detected_language: "Arabic",
    recommended_action: "Alert fan zone security with description and start lost-child protocol.",
    confidence: 0.95,
  },
  {
    id: "seed-005",
    createdAt: Date.now() - 2000000,
    status: "open",
    priority: 60,
    source: "seed",
    originalText: "Long queue at transit hub, buses not arriving on schedule",
    category: "transport",
    severity: 3,
    zone: "transit_hub",
    summary_en: "Long queue at transit hub, buses delayed.",
    detected_language: "English",
    recommended_action: "Contact transport coordinator to dispatch additional buses.",
    confidence: 0.88,
  },
  {
    id: "seed-006",
    createdAt: Date.now() - 1600000,
    status: "open",
    priority: 70,
    source: "seed",
    originalText: "A group of fans is climbing the fence near the west stand",
    category: "security",
    severity: 4,
    zone: "west_stand",
    summary_en: "Fans attempting to climb fence at the west stand.",
    detected_language: "English",
    recommended_action: "Dispatch security team to west stand perimeter immediately.",
    confidence: 0.93,
  },
  {
    id: "seed-007",
    createdAt: Date.now() - 1200000,
    status: "resolved", // Pre-resolved to show resolved state
    priority: 30,
    source: "seed",
    originalText: "Les toilettes du côté nord sont bouchées",
    category: "facility",
    severity: 2,
    zone: "north_gate",
    summary_en: "Toilets on the north side are blocked.",
    detected_language: "French",
    recommended_action: "Send maintenance crew to north gate restrooms.",
    confidence: 0.91,
  },
  {
    id: "seed-008",
    createdAt: Date.now() - 800000,
    status: "open",
    priority: 55,
    source: "seed",
    originalText: "駐車場でライトが消えていて暗くて危ない",
    category: "facility",
    severity: 3,
    zone: "parking",
    summary_en: "Parking lot lights are out, dangerous darkness.",
    detected_language: "Japanese",
    recommended_action: "Send electrician to parking area. Deploy temporary lighting.",
    confidence: 0.87,
  },
  {
    id: "seed-009",
    createdAt: Date.now() - 600000,
    status: "open",
    priority: 65,
    source: "seed",
    originalText: "Crowding is getting worse at the concourse near food stalls",
    category: "crowding",
    severity: 3,
    zone: "concourse",
    summary_en: "Increasing crowd density at concourse food stalls.",
    detected_language: "English",
    recommended_action: "Open overflow service points and redirect foot traffic.",
    confidence: 0.86,
  },
  {
    id: "seed-010",
    createdAt: Date.now() - 400000,
    status: "resolved", // Pre-resolved
    priority: 40,
    source: "seed",
    originalText: "O elevador do lado leste não está funcionando",
    category: "accessibility",
    severity: 2,
    zone: "east_stand",
    summary_en: "East side elevator is not working.",
    detected_language: "Portuguese",
    recommended_action: "Report to maintenance. Direct users to alternative accessible route.",
    confidence: 0.89,
  },
  {
    id: "seed-011",
    createdAt: Date.now() - 300000,
    status: "open",
    priority: 50,
    source: "seed",
    originalText: "There's a suspicious unattended bag near the south gate entrance",
    category: "security",
    severity: 3,
    zone: "south_gate",
    summary_en: "Suspicious unattended bag near south gate entrance.",
    detected_language: "English",
    recommended_action: "Evacuate immediate area and alert bomb squad / security sweep team.",
    confidence: 0.94,
  },
  {
    id: "seed-012",
    createdAt: Date.now() - 200000,
    status: "open",
    priority: 45,
    source: "seed",
    originalText: "No accessible seating left in the east stand, wheelchair user turned away",
    category: "accessibility",
    severity: 3,
    zone: "east_stand",
    summary_en: "No accessible seating available in east stand.",
    detected_language: "English",
    recommended_action: "Check overflow accessible seating. Escort to alternative viewing area.",
    confidence: 0.9,
  },
  // --- Sustainability seed incidents ---
  {
    id: "seed-013",
    createdAt: Date.now() - 150000,
    status: "open",
    priority: 40,
    source: "seed",
    originalText: "Overflowing waste bins near the fan zone, rubbish everywhere on the ground",
    category: "sustainability",
    severity: 3,
    zone: "fan_zone",
    summary_en: "Overflowing waste bins near fan zone, litter on ground.",
    detected_language: "English",
    recommended_action: "Deploy waste management crew to fan zone. Add temporary bins.",
    confidence: 0.88,
  },
  {
    id: "seed-014",
    createdAt: Date.now() - 100000,
    status: "open",
    priority: 35,
    source: "seed",
    originalText: "Water leak at the north gate concession stand, big puddle forming",
    category: "sustainability",
    severity: 2,
    zone: "north_gate",
    summary_en: "Water leak at north gate concession, puddle forming.",
    detected_language: "English",
    recommended_action: "Send plumber to north gate concession. Place wet floor signs.",
    confidence: 0.85,
  },
];

/**
 * Hardcoded incidents for the "Simulate matchday" button.
 * These are added with staggered timestamps to simulate arriving reports.
 */
export const MATCHDAY_SIMULATION: Omit<Incident, "id" | "createdAt">[] = [
  {
    status: "open",
    priority: 80,
    source: "seed",
    originalText: "Huge rush at north gate, people can barely move",
    category: "crowding",
    severity: 4,
    zone: "north_gate",
    summary_en: "Massive crowd surge at north gate, movement restricted.",
    detected_language: "English",
    recommended_action: "Open emergency lanes at north gate. Deploy crowd control.",
    confidence: 0.91,
  },
  {
    status: "open",
    priority: 70,
    source: "seed",
    originalText: "Un hombre mayor se cayó en las escaleras del lado oeste",
    category: "medical",
    severity: 4,
    zone: "west_stand",
    summary_en: "Elderly man fell on the west stand stairs.",
    detected_language: "Spanish",
    recommended_action: "Dispatch medical team to west stand staircase.",
    confidence: 0.93,
  },
  {
    status: "open",
    priority: 55,
    source: "seed",
    originalText: "Parking lot exit is jammed, nobody can leave",
    category: "transport",
    severity: 3,
    zone: "parking",
    summary_en: "Parking lot exit completely blocked, vehicles stuck.",
    detected_language: "English",
    recommended_action: "Send traffic control to parking exit. Open alternate exit.",
    confidence: 0.87,
  },
  {
    status: "open",
    priority: 65,
    source: "seed",
    originalText: "المصاعد في الجناح الشرقي لا تعمل والأشخاص ذوي الإعاقة عالقون",
    category: "accessibility",
    severity: 4,
    zone: "east_stand",
    summary_en: "East stand elevators not working, disabled persons stranded.",
    detected_language: "Arabic",
    recommended_action: "Dispatch staff with portable ramp. Escalate elevator repair.",
    confidence: 0.92,
  },
  {
    status: "open",
    priority: 45,
    source: "seed",
    originalText: "Recycling bins are mixed up with regular trash at concourse",
    category: "sustainability",
    severity: 2,
    zone: "concourse",
    summary_en: "Recycling bins mislabeled at concourse, waste mixing.",
    detected_language: "English",
    recommended_action: "Send waste team to re-sort and relabel concourse bins.",
    confidence: 0.84,
  },
];
